version: '3'
services:
  springboot:
    build: ./springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  flask-ai:
    build: ./flask-ai
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
