spring:

  datasource:
    url: jdbc:mysql://dailycheck.cjkeiaimumut.ap-northeast-2.rds.amazonaws.com:3306/dailycheck
    username: root
    password: kwon0919
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  jwt:
    secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
    expiration_time: 86400000
